# Generated by Django 5.0.14 on 2026-07-15 19:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('letterhead', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=12)),
                ('schema', models.JSONField(blank=True, default=list)),
                ('approval_flow', models.JSONField(blank=True, default=list)),
                ('letterhead_mode', models.CharField(choices=[('none', 'No letterhead (simple)'), ('active', 'Company default (active letterhead)'), ('specific', 'A specific letterhead')], default='none', max_length=10)),
                ('is_anonymous_ref', models.BooleanField(default=False, help_text='Reserved for future public-link submissions.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_templates_created', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_templates_edited', to=settings.AUTH_USER_MODEL)),
                ('letterhead', models.ForeignKey(blank=True, help_text='Used only when letterhead_mode = specific.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_templates', to='letterhead.letterheadtemplate')),
            ],
            options={
                'verbose_name': 'Form template',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('schema_snapshot', models.JSONField(default=list)),
                ('data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='in_review', max_length=12)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='form_submissions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='customforms.formtemplate')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=120)),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('sign', 'Approve + signature')], default='approve', max_length=10)),
                ('assignee_type', models.CharField(choices=[('user', 'Specific user'), ('role', 'Anyone with role'), ('position', 'Anyone with position'), ('unit', 'Anyone in unit'), ('submitter_choice', 'Submitter chooses at submission')], max_length=20)),
                ('assignee_value', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], db_index=True, default='waiting', max_length=10)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('signature_data', models.TextField(blank=True, default='')),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_steps_acted', to=settings.AUTH_USER_MODEL)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_steps_assigned', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='customforms.formsubmission')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('submission', 'order')},
            },
        ),
    ]
