"""
apps/meetings/urls.py

Included from the root URLconf as:
    path('meetings/', include('apps.meetings.urls')),

NOTE: no `app_name` is set on purpose. apps/meetings/views.py redirects with
flat names — redirect('meeting_list'), redirect('meeting_detail', pk=...),
redirect('meeting_minutes', pk=...) — and templates use {% url 'meeting_list' %}.
Adding a namespace here would break all of those.
"""

from django.urls import path

from apps.meetings import views
from apps.meetings import ai_views

urlpatterns = [
    # ─────────────────────────────────────────────
    # LIST
    # Supports ?view=upcoming|... , ?q=<search> , ?type=<meeting_type>
    # (project_detail.html links here with ?q=<project name>)
    # ─────────────────────────────────────────────
    path('',
         views.MeetingListView.as_view(),
         name='meeting_list'),

    # ─────────────────────────────────────────────
    # CREATE
    # MeetingFollowUpView redirects to /meetings/create/?follow_up_from=<pk>
    # ─────────────────────────────────────────────
    path('create/',
         views.MeetingCreateView.as_view(),
         name='meeting_create'),

    # ─────────────────────────────────────────────
    # 📅 CALENDAR FEED (month grid on the list page)
    # GET ?start=YYYY-MM-DD&end=YYYY-MM-DD → JSON events
    # ─────────────────────────────────────────────
    path('calendar/feed/',
         ai_views.MeetingCalendarFeedView.as_view(),
         name='meeting_calendar_feed'),

    # ─────────────────────────────────────────────
    # 🔓 PUBLIC — EXTERNAL MINUTES REVIEW (token link, no login)
    # Declared before the <uuid:pk> routes so a static prefix can never be
    # shadowed. Token is generated by _generate_review_token(), so <str:>.
    # ─────────────────────────────────────────────
    path('minutes/review/<str:token>/',
         views.MeetingMinutesExternalReviewView.as_view(),
         name='meeting_minutes_external_review'),

    # ─────────────────────────────────────────────
    # DETAIL & EDIT
    # ─────────────────────────────────────────────
    path('<uuid:pk>/',
         views.MeetingDetailView.as_view(),
         name='meeting_detail'),

    path('<uuid:pk>/edit/',
         views.MeetingUpdateView.as_view(),
         name='meeting_edit'),

    path('<uuid:pk>/follow-up/',
         views.MeetingFollowUpView.as_view(),
         name='meeting_follow_up'),

    path('<uuid:pk>/follow-up/',
         views.MeetingFollowUpView.as_view(),
         name='meeting_followup'),

    # ─────────────────────────────────────────────
    # LIFECYCLE ACTIONS (all POST-only)
    # ─────────────────────────────────────────────
    path('<uuid:pk>/rsvp/',
         views.MeetingRSVPView.as_view(),
         name='meeting_rsvp'),

    path('<uuid:pk>/cancel/',
         views.MeetingCancelView.as_view(),
         name='meeting_cancel'),

    path('<uuid:pk>/end/',
         views.MeetingEndView.as_view(),
         name='meeting_end'),

    path('<uuid:pk>/attendance/',
         views.MeetingAttendanceUpdateView.as_view(),
         name='meeting_attendance_update'),

    # ─────────────────────────────────────────────
    # MINUTES
    # _notify_external_for_adoption() links to /meetings/<pk>/minutes/
    # ─────────────────────────────────────────────
    path('<uuid:pk>/minutes/',
         views.MeetingMinutesView.as_view(),
         name='meeting_minutes'),

    path('<uuid:pk>/minutes/pdf/',
         views.MeetingMinutesPDFView.as_view(),
         name='meeting_minutes_pdf'),

    path('<uuid:pk>/minutes/share/',
         views.ShareMeetingMinutesView.as_view(),
         name='share_meeting_minutes'),

    # ─────────────────────────────────────────────
    # 🎙️ RECORDINGS (ai_views) — all JSON/XHR
    # GET  list · POST upload (audio, title, duration_seconds)
    # ─────────────────────────────────────────────
    path('<uuid:pk>/recordings/',
         ai_views.MeetingRecordingView.as_view(),
         name='meeting_recordings'),

    # GET status+transcript · POST action=transcribe|rename|delete
    path('<uuid:pk>/recordings/<uuid:rid>/',
         ai_views.MeetingRecordingManageView.as_view(),
         name='meeting_recording_manage'),

    # ─────────────────────────────────────────────
    # 🤖 MINUTES EDITOR HELPERS (ai_views) — POST only
    # ─────────────────────────────────────────────
    # Debounced silent draft save; touches content + decisions only.
    path('<uuid:pk>/minutes/autosave/',
         ai_views.MinutesAutosaveView.as_view(),
         name='minutes_autosave'),

    # Drafts minutes from transcripts. Optional body field: recording_id.
    # Returns HTML for review — writes nothing to the minutes itself.
    path('<uuid:pk>/minutes/ai-draft/',
         ai_views.MinutesAIDraftView.as_view(),
         name='minutes_ai_draft'),
]