"""
apps/finance/audit_models.py
=============================

Models that power the financial audit trail. These are designed to be
*appended* to your existing apps/finance/models.py — copy the contents
below into the bottom of that file (so they live under the same app
label).

Two models
----------
1. FinanceAuditLog — append-only journal of every create/update/delete
   on every financial model. Captures actor, IP, before/after diff.

2. FinanceAnomaly — flagged events for review. Generated by the anomaly
   detector (signals.py), can be acknowledged by CEO/Admin.
"""
import uuid
from django.db import models
from django.utils import timezone

# NB: when copying into models.py the User import is already there.
# Showing the full path here for clarity in this standalone file.
from apps.core.models import User


class FinanceAuditLog(models.Model):
    """
    Append-only journal. Never updated, never deleted (except by superuser
    DB intervention). Indexed on (model, object_id) for fast per-record
    history lookups.
    """

    class Action(models.TextChoices):
        CREATE  = 'create',  'Created'
        UPDATE  = 'update',  'Updated'
        DELETE  = 'delete',  'Deleted'
        APPROVE = 'approve', 'Approved'
        REJECT  = 'reject',  'Rejected'
        PAY     = 'pay',     'Paid'
        CANCEL  = 'cancel',  'Cancelled'
        SEND    = 'send',    'Sent'
        EXPORT  = 'export',  'Exported'
        VIEW    = 'view',    'Viewed Sensitive'

    id          = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    # Who, when, where
    actor       = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True,
                                    related_name='finance_audit_actions')
    actor_name  = models.CharField(max_length=200, blank=True,
                                   help_text='Snapshot of name at time of action')
    ip_address  = models.GenericIPAddressField(null=True, blank=True)
    user_agent  = models.CharField(max_length=300, blank=True)
    timestamp   = models.DateTimeField(auto_now_add=True, db_index=True)

    # What
    action      = models.CharField(max_length=20, choices=Action.choices)
    model_name  = models.CharField(max_length=100, db_index=True,
                                   help_text='e.g. "Payment", "PurchaseRequest"')
    object_id   = models.CharField(max_length=64, db_index=True, blank=True)
    object_repr = models.CharField(max_length=300, blank=True,
                                   help_text='__str__ snapshot in case the object is deleted')

    # Financial signal — money amount involved, if any
    amount      = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    currency    = models.CharField(max_length=10, blank=True)

    # Diff
    changes     = models.JSONField(default=dict, blank=True,
                                   help_text='{"field": [old, new]} for updates')

    # Free text describing the action
    notes       = models.TextField(blank=True)

    class Meta:
        ordering = ['-timestamp']
        indexes = [
            models.Index(fields=['model_name', 'object_id']),
            models.Index(fields=['action', '-timestamp']),
            models.Index(fields=['actor', '-timestamp']),
        ]
        verbose_name = 'Finance Audit Log Entry'
        verbose_name_plural = 'Finance Audit Trail'

    def __str__(self):
        who = self.actor_name or (self.actor and self.actor.get_full_name()) or 'System'
        return f'{who} {self.get_action_display()} {self.model_name} {self.object_repr}'


class FinanceAnomaly(models.Model):
    """
    A red flag raised by the anomaly detector. CEO/Admin can review and
    resolve. Anomalies link back to the AuditLog row that triggered them.
    """

    class Severity(models.TextChoices):
        LOW    = 'low',    'Low'
        MEDIUM = 'medium', 'Medium'
        HIGH   = 'high',   'High'

    class Status(models.TextChoices):
        OPEN      = 'open',      'Open'
        REVIEWING = 'reviewing', 'Under Review'
        RESOLVED  = 'resolved',  'Resolved'
        DISMISSED = 'dismissed', 'Dismissed'

    class Kind(models.TextChoices):
        DUPLICATE_AMOUNT = 'duplicate_amount', 'Duplicate Payment Amount'
        OFF_HOURS_EDIT   = 'off_hours_edit',   'Off-Hours Edit'
        WEEKEND_PAYMENT  = 'weekend_payment',  'Weekend Payment'
        BUDGET_OVERRUN   = 'budget_overrun',   'Budget Overrun'
        LARGE_AMOUNT     = 'large_amount',     'Unusually Large Amount'
        RAPID_APPROVAL   = 'rapid_approval',   'Rapid Self-Approval'
        BACKDATED        = 'backdated',        'Backdated Transaction'
        DUPLICATE_VENDOR = 'duplicate_vendor', 'Possible Duplicate Vendor'

    id          = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    kind        = models.CharField(max_length=30, choices=Kind.choices)
    severity    = models.CharField(max_length=10, choices=Severity.choices, default=Severity.MEDIUM)
    status      = models.CharField(max_length=20, choices=Status.choices, default=Status.OPEN)

    title       = models.CharField(max_length=200)
    description = models.TextField()

    # What it points to
    model_name  = models.CharField(max_length=100, blank=True)
    object_id   = models.CharField(max_length=64, blank=True)
    audit_entry = models.ForeignKey(FinanceAuditLog, on_delete=models.SET_NULL,
                                     null=True, blank=True, related_name='anomalies')

    # Context
    amount      = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    currency    = models.CharField(max_length=10, blank=True)
    extra       = models.JSONField(default=dict, blank=True)

    # Workflow
    detected_at = models.DateTimeField(auto_now_add=True, db_index=True)
    reviewed_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True,
                                     related_name='reviewed_anomalies')
    reviewed_at = models.DateTimeField(null=True, blank=True)
    resolution  = models.TextField(blank=True)

    class Meta:
        ordering = ['-detected_at']
        indexes = [
            models.Index(fields=['status', '-detected_at']),
            models.Index(fields=['severity', 'status']),
        ]
        verbose_name = 'Finance Anomaly'
        verbose_name_plural = 'Finance Anomalies'

    def __str__(self):
        return f'[{self.severity.upper()}] {self.title}'

    @property
    def severity_color(self):
        return {
            'low':    '#f59e0b',
            'medium': '#f97316',
            'high':   '#ef4444',
        }.get(self.severity, '#94a3b8')

    @property
    def status_color(self):
        return {
            'open':      '#ef4444',
            'reviewing': '#f59e0b',
            'resolved':  '#10b981',
            'dismissed': '#94a3b8',
        }.get(self.status, '#94a3b8')
